### PR TITLE
Fix/error handling cleanup

### LINKED ISSUE #40: Improve / Standardize Error Handling on Backend
# Task 🔨
Implement the changes discussed here to our error handling
https://github.com/ubclaunchpad/when3meet/pull/39

### PR DESCRIPTION
**Pull request by jamesmengo**
## Overview ⚙️

- Standardize error handling
1) Set response
2) Basic description
3) Clean up the response by preventing the request body from being sent back

## Related Issues ⚠️

https://github.com/ubclaunchpad/when3meet/issues/40

Closes #40

### CODE REVIEW

**Comment by jamesmengo** [comment]
Note that this build off of PR#1.

**Comment by jackyzha0** [comment]
> Note that this build off of PR#1.

can you rebase off of master and resubmit?

File: backend/test_firestore.go [hunk 1]
```diff
@@ -9,43 +9,46 @@ import (
...
 	event := &firebase.Event{}
 	err := json.NewDecoder(r.Body).Decode(&event)
 	if err != nil {
-		w.WriteHeader(http.StatusBadRequest)
 		log.Warnf("Failed to decode the request: %v", err)
+		http.Error(w,"Failed to decode the provided event", http.StatusBadRequest)
 		return
 	}
-	log.Infof("Creating event with data: %+v", event)
+	log.Printf("Creating event with data: %+v", event)
```
Comment (jackyzha0) [inline backend/test_firestore.go]: why print instead of info?

**Review by jackyzha0 — APPROVED** [review]
small comment, but looks good

File: backend/test_firestore.go (hunk 1 above)
Comment (jamesmengo) [reply backend/test_firestore.go]: Good point I think that they both log to INFO level but using PrintF will log even if info level logs are not enabled. I agree that we should be using an actual logging level instead of print so I'll change this

**Review by nandanmen — APPROVED** [review]
